services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=studyu_flow_db'
      - 'POSTGRES_PASSWORD=studyu_flow_2025_admin'
      - 'POSTGRES_USER=azocar'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/data/postgres'
  api:
    build: .
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - '8080:8080'
volumes:
  pgdata: